version: '3.7'

services:
  feedstock-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: feedstock-php
    restart: on-failure
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./setup/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - fs-network
  
  feedstock-nginx:
    image: nginx:latest
    container_name: feedstock-nginx
    restart: on-failure
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./setup/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - fs-network

  feedstock-database:
    image: mysql:5.7
    container_name: feedstock-database
    restart: on-failure
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "feedstock"
      MYSQL_ROOT_PASSWORD: "6Idol-Signs3"
      MYSQL_USER: "fs"
      MYSQL_PASSWORD: "fs-db2907"
    volumes:
      - ./db:/var/lib/mysql
      - ./setup/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - fs-network

networks:
    fs-network:
        driver: bridge

volumes:
    db:
        driver: local
